### ISSUE TITLE
weather icons don't like to keep their palettes in double battles

### ISSUE THREAD

**Issue by BluRosie** [BluRosie/hg-engine#121]
![image](https://github.com/BluRosie/hg-engine/assets/16446370/8a1a5312-51bb-4517-aa30-380293452bc7)

**Comment by SergooPoke** [comment]
issue encountered in wild double battle -- multi battles untested.

**Comment by NathanWichers** [comment]
end of turn updating also broke

**Comment by BluRosie** [comment]
end of turn updating also appears to have broken

**Comment by NathanWichers** [comment]
ServerFieldConditionCheck
