### ISSUE TITLE
New Rom Not Appearing in the Folder

### ISSUE THREAD

**Issue by VolcaCake** [BluRosie/hg-engine#185]
I did it over and over again I renamed my rom, rom.nds like it said everything was successful but the new rom doesn't appear in the folder.

**Comment by BluRosie** [comment]
so...  it says "Done" and there's no rom there?

**Comment by BluRosie** [comment]
has been a week since updates--i'm closing this now.  check out the [kingdom of ds hacking discord server](https://discord.gg/zAtqJDW2jC) for further help
