### ISSUE TITLE
Game crashes when catching alt. forms

### ISSUE THREAD

**Issue by FrostFalcon** [BluRosie/hg-engine#195]
More specifically, it seems to crash when attempting to open the pokedex description screen right after you catch a pokemon. It happened when I tried it with alolan rattata and yellow flabebe, but I imagine the issue occurs with all alternate forms. While I'm here, I'd also like to mention that the alt. forms' names aren't displayed. They appear as "-----" in game.

**Comment by BluRosie** [comment]
assuming you have added them using the encounter tables or something, the form system is designed such that the base species is all you need and the form id goes from there.  form id can be looked up per mon in the file [`data/PokeFormDataTbl.c`](https://github.com/BluRosie/hg-engine/blob/main/data/PokeFormDataTbl.c)
take a look at a few of the documentation pages, particularly [Form System Documentation](https://github.com/BluRosie/hg-engine/wiki/Form-System-Documentation) and [Wild Pokémon Documentation](https://github.com/BluRosie/hg-engine/wiki/Wild-Pok%C3%A9mon-Table-Documentation)
so the solution for alolan rattata would be `monwithform SPECIES_RATTATA, 1` and something like orange flabebe would be `monwithform SPECIES_FLABEBE, 2` (see the orange flower flabebe's entry in the file)
```c
    {
        .species = SPECIES_FLABEBE,
        .form_no = 2,
        .need_rev = 0,
        .file = SPECIES_FLABEBE_ORANGE_FLOWER,
    },
```

**Comment by FrostFalcon** [comment]
Ok, I think I get it. I've been using a modified DSPRE for most edits, though I'm still figuring out all the tools that need to be fixed for the engine. Just out of curiosity, is there a c script for encounters in the engine? I think it'd be cool to edit it to add things like level variance or encounter weights that aren't based on slots

**Comment by BluRosie** [comment]
a c script for encounters...  like is the function exposed?  `AddWildPartyPokemon` is exposed in ['src/field/enemy_party.c'](https://github.com/BluRosie/hg-engine/blob/main/src/field/enemy_party.c#L479)
that doesn't cover the encounter weights tho.

**Comment by FrostFalcon** [comment]
I see. I'll look into that on my own. Thanks for the help!

**Comment by BluRosie** [comment]
no problem!  if you have a discord, you could probably get much quicker help on the [KoDSH discord server](https://discord.gg/zAtqJDW2jC) if convenience is a worry for you

**Comment by FrostFalcon** [comment]
I've added the form functionality to my editor and it all seems to be working. Thanks again.
