### ISSUE TITLE
Infinite uses for TMs

### ISSUE THREAD

**Issue by FegDotExe** [BluRosie/hg-engine#213]
I suggest infinite uses for tms are implemented, following how they are from gen 5 onwards.

**Comment by BluRosie** [comment]
it is on by default, see [`armips/include/config.s`](https://github.com/BluRosie/hg-engine/blob/main/armips/include/config.s#L41)

**Comment by FegDotExe** [comment]
I couldn't find any info in the documentation, I may be stupid lol.
Thx for the reply though :)
