### ISSUE TITLE
Variations of Normalize should not affect certain moves

### ISSUE THREAD

**Issue by Aeliko** [BluRosie/hg-engine#226]
Judgment is unaffected by [Normalize](https://bulbapedia.bulbagarden.net/wiki/Normalize_(Ability)), [Pixilate](https://bulbapedia.bulbagarden.net/wiki/Pixilate_(Ability)), [Refrigerate](https://bulbapedia.bulbagarden.net/wiki/Refrigerate_(Ability)), and [Aerilate](https://bulbapedia.bulbagarden.net/wiki/Aerilate_(Ability)). However, it is affected by [Ion Deluge](https://bulbapedia.bulbagarden.net/wiki/Ion_Deluge_(move)) (if the move would be Normal-type) and [Electrify](https://bulbapedia.bulbagarden.net/wiki/Electrify_(move))

[Hidden Power](https://bulbapedia.bulbagarden.net/wiki/Hidden_Power_(move)), [Weather Ball](https://bulbapedia.bulbagarden.net/wiki/Weather_Ball_(move)), [Natural Gift](https://bulbapedia.bulbagarden.net/wiki/Natural_Gift_(move)), [Judgment](https://bulbapedia.bulbagarden.net/wiki/Judgment_(move)), and [Techno Blast](https://bulbapedia.bulbagarden.net/wiki/Techno_Blast_(move)) are not affected by Normalize.

[Multi-Attack](https://bulbapedia.bulbagarden.net/wiki/Multi-Attack_(move)), [Terrain Pulse](https://bulbapedia.bulbagarden.net/wiki/Terrain_Pulse_(move)) and damaging [Z-Moves](https://bulbapedia.bulbagarden.net/wiki/Z-Move) are not affected by Normalize.

Tested in Showdown, Judgment and Techno Blast are not affected by Pixilate

**Comment by BluRosie** [comment]
fixed with that merged PR
