### ISSUE TITLE
King's Rock

### ISSUE THREAD

**Issue by Aeliko** [BluRosie/hg-engine#256]
Generations III and IV

Grants the moves listed below a 10% chance of causing each target to flinch. ~~This chance is not affected by [Serene Grace](https://bulbapedia.bulbagarden.net/wiki/Serene_Grace_(Ability)).~~

Each strike of a [multi-strike move](https://bulbapedia.bulbagarden.net/wiki/Multi-strike_move) has an independent chance of causing the target to flinch. Flinching caused this way is no longer different to flinching caused by other means.
Generation V onward

**Grants all attacking moves that do not already have a chance to flinch a 10% chance of causing each target to flinch. This chance is affected by [Serene Grace](https://bulbapedia.bulbagarden.net/wiki/Serene_Grace_(Ability)) and the rainbow created by [Fire Pledge](https://bulbapedia.bulbagarden.net/wiki/Fire_Pledge_(move)) and [Water Pledge](https://bulbapedia.bulbagarden.net/wiki/Water_Pledge_(move)).** King's Rock does not activate [Sheer Force](https://bulbapedia.bulbagarden.net/wiki/Sheer_Force_(Ability)), but Sheer Force removes the chance to flinch if the move already has an [additional effect](https://bulbapedia.bulbagarden.net/wiki/Additional_effect).

**Comment by BluRosie** [comment]
going to create the project for updating old items based on https://bulbapedia.bulbagarden.net/wiki/User:MisterE13/List_of_modified_items
