### ISSUE TITLE
fedora specific issue?

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [BluRosie/hg-engine#274]
"requested access to resource is denied" when running the docker file "docker-makerom" the other linux native method gives error 127 upon running "make". (repeated error 127 if doing make --jobs (fedora)) possibly related to #139

**Comment by BluRosie** [comment]
i'll have to set up a fedora system and check this out

**Comment by BluRosie** [comment]
> "requested access to resource is denied" when running the docker file "docker-makerom" the other linux native method gives error 127 upon running "make". (repeated error 127 if doing make --jobs (fedora)) possibly related to #139

what error 127 is it giving you?  like what doesn't exist

**Comment by OrdinaryCloverOC** [comment]
i have absolutely no idea what i did to the file before making this post. i had to switch out "docker" with podman in every cmd file to make it work, but i forgot what i did from there. currently the error says "no targets specified and no makefile found" although i have a makefile. i realize this is not exactly customer support, but i have no idea what i am doing, and might resort to distrobox. i apologize for any potential confusion this error gave, unless i encounter it once again upon realizing how to work this all over again. also i noticed it auto-downloaded a bunch of ubuntu files even though i'm on fedora.

**Comment by BluRosie** [comment]
is there a reason you're using docker then?  docker looks to essentially run a ubuntu environment to build everything from scratch.  podman is something that ties it all in.  and to be clear--you are running `./docker-makerom.cmd` (after editing the `docker` to be `podman` or whatever) and it's not mounting the hg-engine folder correctly?  are you able to `./docker-login.cmd` and then inside of the container verify that there's an hg-engine folder in there with `ls -a`
can then:
```
cd hg-engine
make -j$(nproc)
```
and see if that still fails you
