### ISSUE TITLE
Wrong Seed Flavour Text

### ISSUE THREAD

**Issue by Aeliko** [BluRosie/hg-engine#294]
![image](https://github.com/user-attachments/assets/6109a93f-fafc-431f-8027-6945bd9123df)
![image](https://github.com/user-attachments/assets/6df6dab8-00d7-4f1e-909a-554416fafe76)

**Comment by BluRosie** [comment]
man smogon is not the standard wrt flavor text

**Comment by Aeliko** [comment]
![Screenshot_20240721-075658.png](https://github.com/user-attachments/assets/aeaa9faa-adbf-4016-b287-17324f1b25e1)

Found an accurate screenshot instead

**Comment by BluRosie** [comment]
![image](https://github.com/user-attachments/assets/b79e2379-0426-4cfe-b031-b24ed1500d6a)
