### ISSUE TITLE
Setup instructions yield compiler error

### ISSUE THREAD

**Issue by philberns** [BluRosie/hg-engine#299]
Following the setup instructions for WSL for windows yield the following compiler error. I have reinstalled everything apart from a clean Windows install (WSL, Ubuntu, etc.) and the issue persists. Is there a linking -lm flag missing somewhere? 
![error](https://github.com/user-attachments/assets/f32fe1b2-5fd4-4b02-8504-0a1a36e44f1f)

**Comment by swirl9595** [comment]
same problem here

**Comment by BluRosie** [comment]
looks like the tool we use for some cry conversions recently updated and now does some fun log10 stuff.  will make this a git submodule soon so everything is properly checked out
really should do the same to ndstool and friends too

**Comment by BluRosie** [comment]
fixed with c458d9962dc5e81f53748a484466c72b9b1f41ca, let me know if anything else pops up
