### ISSUE TITLE
Changed mon data and these errors happened.

### ISSUE THREAD

**Issue by W00P23** [BluRosie/hg-engine#300]
![image_2024-08-10_150528065](https://github.com/user-attachments/assets/cc79b863-4d95-4d35-8c3c-5ebf86c1ac8c)

I don't know how to fix this cause i'm new to this engine and don't know what it means
I changed pokemon secondary types, stats, and abilities

**Comment by W00P23** [comment]
[armips.zip](https://github.com/user-attachments/files/16626900/armips.zip)
I don't know if this is right I didn't know how to upload it except for .zip
Also I seemed to fix most of them the only ones that still make errors are these 2 
![Screenshot 2024-08-15 102656](https://github.com/user-attachments/assets/930de46d-76cd-4ef0-bcae-533757f3081d)

**Comment by BluRosie** [comment]
looks like one of those at least is that you must have deleted the `m` in `mondata` somewhere

looks like another one may be an issue with some mon's `basestats` potentially not having enough arguments provided or something?

**Comment by W00P23** [comment]
I was able to fix the first one and would change the basestats of pokemon back to what they were be a way to fix the 47 error

**Comment by W00P23** [comment]
Do you happen to know anything I can do to fix this error like am I needing to change the stats back or do I need to look for a certain error in typing them
