### ISSUE TITLE
Fishious Rend changes to 

### ISSUE THREAD

**Issue by darklordarbitur** [BluRosie/hg-engine#306]
When editing a pokemon's moveset in DSPRE, Fishious Rend becomes Ancient Power after saving and reopening the file.

Note below, a freshly saved Totodile with Fishious Rend.
![image_2024-08-22_160804613](https://github.com/user-attachments/assets/a913c6f1-79fd-4859-a167-742246b54603)

After saving, closing, and getting a freshly unpacked and recompiled .nds file, note Ancient Power in the level 50 slot.
![image_2024-08-22_161135466](https://github.com/user-attachments/assets/8ebf6398-7336-438d-9f2a-532cd833b985)

**Comment by BluRosie** [comment]
if you are using hg-engine, the learnsets all use a new format that is a foreign to DSPRE
i would rather recommend editing the learnsets in hg-engine (through `armips/data/levelupdata.s`), since hg-engine will by default overwrite the learnsets on recompiling anyway
