### ISSUE TITLE
Questions about EV/IV Viewer

### ISSUE THREAD

**Issue by XiaoFuDieZZZ** [BluRosie/hg-engine#343]
I saw "EV/IV Viewer in the Summary Screen" on the wiki, but I didn't see a specific EV/IV on the pokemon status page

Do I need to press any buttons？

**Comment by XiaoFuDieZZZ** [comment]
![PixPin_2024-10-27_10-06-04](https://github.com/user-attachments/assets/24521a1a-45ee-4cca-b9a5-1744fb520233)

**Comment by BluRosie** [comment]
should be able to press L, R, and Select to toggle each of the modes!  lmk if that works

On Oct 26, 2024, at 22:07, XiaoFuDieZZZ ***@***.***> wrote:

﻿

PixPin_2024-10-27_10-06-04.png (view on web)<https://github.com/user-attachments/assets/24521a1a-45ee-4cca-b9a5-1744fb520233>
