### ISSUE TITLE
Questions about poisoning status

### ISSUE THREAD

**Issue by XiaoFuDieZZZ** [BluRosie/hg-engine#345]
I found that this engine prevented poisoned Pokmon from losing HP in the town area.
I wonder if it is possible to modify a file in the directory \hg-engine\armips if I want to revert to the gen4 state?

**Comment by BluRosie** [comment]
hello!
if you recomment out the `#define UPDATE_OVERWORLD_POISON` (so that it is `//#define UPDATE_OVERWORLD_POISON`), the overworld poison will be reenabled in your rom

did the L/R/Select work for the EV/IV viewer?

**Comment by XiaoFuDieZZZ** [comment]
Yes,it works(EV/IV viewer).

Thank you very much!😄
