### ISSUE TITLE
About Level Caps

### ISSUE THREAD

**Issue by XiaoFuDieZZZ** [BluRosie/hg-engine#352]
Can the maximum level cap be gradually increased by increasing the number of badges earned?Not by a fixed number

**Comment by Aeliko** [comment]
Looking at your issue history you should have access to DSPRE. Enable level caps and assign a value to the following [scripting variable](https://github.com/BluRosie/hg-engine/blob/main/include%2Fconfig.h#L72).

If you have access to YouTube here is a video tutorial: [video tutorial](https://youtu.be/NbITcU1uApo?feature=shared) not made by me.

If you have access to Discord you can ask questions in the server for potentially faster replies by others.

**Comment by XiaoFuDieZZZ** [comment]
Thank you very much！！！It really helped me a lot！！！
 this video very clearly explains what 0x416F does. And all this time I thought it was just a num of level😂
