### ISSUE TITLE
Cannot build test.nds on Docker (M1 Mac)

### ISSUE THREAD

**Issue by EmilyInept** [BluRosie/hg-engine#357]
Building with docker works up until I attempt to build the NDS file. I do have HeartGold in the ~/git/hg-engine directory and it is named rom.nds as the instructions say.

When running ./docker-makerom.cmd I get the following output and several errors:

    rm -rf base
    mkdir -p build/pokemonow build/pokemonicon build/pokemonpic build/a018 build/narc build/text build/move build/a011 build/rawtext
    mkdir -p build/move/move_anim build/move/move_sub_anim build/move/move_anim build/pw_pokegra build/pw_pokeicon build/pw_pokegra_int build/pw_pokeicon_int
    ###The line below is because of junk files that macOS can create which will interrupt the build process###
    find . -name '*.DS_Store' -execdir rm -f {} ;
    tools/ndstool -x rom.nds -9 base/arm9.bin -7 base/arm7.bin -y9 base/overarm9.bin -y7 base/overarm7.bin -d base/root -y base/overlay -t base/banner.bin -h base/header.bin
    Nintendo DS rom tool 2.1.2 - Nov 12 2024
    by Rafael Vuijk, Dave Murphy, Alexei Karpenko
    9i (null), 7i (null), unitcode 0
    rom.nds Decompression successful!!
    python3 tools/narcpy.py extract base/root/a/0/2/8 -o build/a028/ -nf
    python3 scripts/make.py
    Decompress arm9.
    Inserting code.
    make move_narc
    make[1]: Entering directory '/hg-engine'
    python3 tools/narcpy.py extract base/root/a/0/1/2 -o build/a012 -nf
    tools/nitrogfx data/graphics/sprites/none/female/back.png build/pokemonpic/0000-00.NCGR -scanfronttoback -handleempty
    tools/nitrogfx data/graphics/sprites/none/male/back.png build/pokemonpic/0000-01.NCGR -scanfronttoback -handleempty
    tools/nitrogfx: 1: Syntax error: word unexpected (expecting ")")
    make[1]: *** [data/graphics/pokegra.mk:22: build/pokemonpic/0000-00.NCGR] Error 2
    make[1]: *** Waiting for unfinished jobs....
    tools/nitrogfx: 1: Syntax error: word unexpected (expecting ")")
    make[1]: *** [data/graphics/pokegra.mk:24: build/pokemonpic/0000-01.NCGR] Error 2
    for file in armips/scr_seq/scr_seq_00003_commonscript.s; do tools/armips $file; done
    python3 tools/narcpy.py create build/narc/scr_seq.narc build/a012 -nf
    make[1]: Leaving directory '/hg-engine'
    make: *** [Makefile:211: all] Error 2

I have updated to the latest Docker version but this issue persists.

**Comment by BluRosie** [comment]
seems like it's interpreting your `tools/nitrogfx` as like a text file or something?

**Comment by EmilyInept** [comment]
> seems like it's interpreting your `tools/nitrogfx` as like a text file or something?

Destroyed my hg-engine directory and re-ran everything in the readme and it worked. I'm... not entirely sure what was wrong but hey... not gonna complain haha.

Closing.
