### ISSUE TITLE
dpad in battle select moves menu can be uninitialized properly

### ISSUE THREAD

**Issue by BluRosie** [BluRosie/hg-engine#49]
has to do with mega code

**Comment by Bonboon229** [comment]
Can confirm this bug report.
dpad in battles is broken.

**Comment by BluRosie** [comment]
@Bonboon229 so i can't get this to consistently happen.  is it always happening or how do you get this to occur?  last i saw it happen personally was october
do you have a save you could send to me that consistently has it happen?  or even a save state?

**Comment by Bonboon229** [comment]
You already answered my question on discord.
Goji Goodra, at your service. Bonboon229 is my old username. Really need to update it...

**Comment by BluRosie** [comment]
see [convo on discord](https://discord.com/channels/446824489045721090/810895757309771796/1191098765029933186)
seems to legit be an emu issue with "literal optimizations" on in melonDS

**Comment by BluRosie** [comment]
i am closing this because i don't see myself fixing this
